name: Aranya Dutta
author: Aranya Dutta
title: "Aranya Dutta's Blog"
description: "Aranya Dutta's personal website and blog."
keywords: blog programming student resume technology talks
tagline: Learning, One Step at a Time
logo: /images/me.jpg

social:
  github: https://github.com/thisizaro
  instagram: https://instagram.com/thisizaro
  linkedin: https://www.linkedin.com/in/thisisaro
  email: mailto:thisisaro.official@gmail.com

url: https://thisizaro.github.io

plugins: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"

markdown: kramdown
highlighter: rouge
permalink: pretty

kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - README.md
